name: TotalSegmentator to CoreML Conversion

on:
  workflow_dispatch:
    inputs:
      model_version:
        description: 'Model version or tag'
        required: false
        default: 'v1'
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Docker and Docker Compose setup
        run: |
          # Check installed versions
          docker --version
          docker compose version || echo "Docker compose not found as 'docker compose'"
          
          # Create docker-compose compatibility script
          echo '#!/bin/bash' | sudo tee /usr/local/bin/docker-compose
          echo 'docker compose "$@"' | sudo tee -a /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
          # Verify docker-compose command works
          docker-compose --version
      
      - name: Run conversion in Docker
        run: |
          cd MCPs/totalsegmentator-coreml-mcp/docker
          
          # Ensure the conversion script is executable
          chmod +x run_conversion.sh
          
          # Run the conversion script
          ./run_conversion.sh
      
      - name: Upload converted model
        uses: actions/upload-artifact@v4
        with:
          name: TotalSegmentator-CoreML-${{ github.event.inputs.model_version }}
          path: MCPs/totalsegmentator-coreml-mcp/docker/models/
